# Generated by Django 5.2.7 on 2025-10-30 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='responses/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='coachingsite.message')),
            ],
        ),
    ]
