# Generated by Django 5.2.7 on 2025-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingsite', '0004_message_sender_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d'),
        ),
    ]
