# Generated by Django 5.2.7 on 2025-11-09 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingsite', '0005_profile_bio_profile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_athletes',
            field=models.ManyToManyField(blank=True, related_name='assigned_coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
