# Generated by Django 5.2.7 on 2025-11-13 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingsite', '0006_profile_assigned_athletes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('score_relative', models.IntegerField(help_text='Score relative to par (e.g. -2, +5)')),
                ('played_on', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_on', '-created_at'],
            },
        ),
    ]
